### PR TITLE
Update build_script.sh

### PR DESCRIPTION
**Pull request by DRCRecoveryData**
Fix /userdata/roms/ports/m8c.sh: line 41: ./m8c: Permission denied

### CODE REVIEW

**Comment by jamesMcMeex** [comment]
This is a good change - I actually didn't realise that file permission changes are not preserved across systems, so my changes are redundant, your fix is what is needed here - thanks!

However, I think in addition to this change, we should tidy up the other scripts which are also changing the file permissions (ineffectively) of the executable, as they are not helpful.

**Comment by DRCRecoveryData** [comment]
> This is a good change - I actually didn't realise that file permission changes are not preserved across systems, so my changes are redundant, your fix is what is needed here - thanks!
> 
> 
> 
> However, I think in addition to this change, we should tidy up the other scripts which are also changing the file permissions (ineffectively) of the executable, as they are not helpful.

One more issue that docker on windows after compiling it's not create the m8c.sh file just crate the m8c folder only

**Comment by jamesMcMeex** [comment]
> One more issue that docker on windows after compiling it's not create the m8c.sh file just crate the m8c folder only

Open a separate issue for that. I also don't have a Windows machine, so you might need to debug this yourself

**Comment by DRCRecoveryData** [comment]
I've fix m8c.sh missing by compiling on windows and linux issue by:

```https://github.com/jamesMcMeex/m8c-rg35xx-knulli/pull/3/commits/6216037614679eefa64f8af8a7aa6ae17fd8726f```

I use Zorin OS 17.2 to compile with docker but after compiled the output folder locked by premission:

Screenshot from 2024-09-20 21-11-55

Screenshot from 2024-09-20 21-07-33

Only working by command: 

```sudo docker run -v $(pwd)/output:/build/compiled m8c-knulli```

and grant access via:

```sudo chown -R $(whoami):$(whoami) output```

After that:

Screenshot from 2024-09-20 21-12-21

**Comment by DRCRecoveryData** [comment]
> I've removed the unnecessary file permission changes - please take a look!

I confirmed this working!

**Comment by jamesMcMeex** [comment]
Testing on those systems is a great help as I don't have easy access to them - thank you!

**Comment by DRCRecoveryData** [comment]
Adding some note that using FileZilla on linux use to transfer file to RG40XX H by network ssh:

Host name: 	KNULLI
Port: 	22
User name: 	root
Password: 	linux

Screenshot from 2024-09-20 21-15-35

FileZilla install by:

```sudo snap install filezilla```

**Comment by DRCRecoveryData** [comment]
Also do you have guide to adding image of m8tracker to the right like game rom image?

**Comment by jamesMcMeex** [comment]
In the README: https://github.com/jamesMcMeex/m8c-rg35xx-knulli?tab=readme-ov-file#installation-on-device-knulli-cfw-specific

**Pull request merged**
